version: 2
services:
  mysql:





    image: debezium/example-mysql:1.2
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    volumes:
      - ${PWD}/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql